public enum pointcloud_state {
  POINTCLOUD_NOT_CREATED,
  POINTCLOUD_WAITING_FOR_CAMERA_FRAMES,
  POINTCLOUD_IDLE,
  POINTCLOUD_INITIALIZING,
  POINTCLOUD_TRACKING_SLAM_MAP,
  POINTCLOUD_RELOCALIZING,
  POINTCLOUD_LOOKING_FOR_IMAGES,
  POINTCLOUD_TRACKING_IMAGES
}
